alias fuck='sudo `fc -n -l -1`'

# yay zsh-autosuggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source ~/.oh-my-zsh/custom/zsh_autosuggestion.zsh

#unalias htop
alias htop="htop --tree"
