#!/bin/bash


INCREMENT_BRIGHTNESS="50"
ROOT_BRIGHTNESS="/sys/class/backlight/intel_backlight"
MAX_BRIGHTNESS=$(cat $ROOT_BRIGHTNESS/max_brightness)
CURRENT_BRIGHTNESS=$(cat $ROOT_BRIGHTNESS/actual_brightness)

COMPUTED_BRIGHTNESS=$(($CURRENT_BRIGHTNESS+$INCREMENT_BRIGHTNESS))

#MIN COMPUTED_BRIGHTNESS MAX_BRIGHTNESS
COMPUTED_BRIGHTNESS=$(($COMPUTED_BRIGHTNESS>$MAX_BRIGHTNESS?$MAX_BRIGHTNESS:$COMPUTED_BRIGHTNESS))
echo $COMPUTED_BRIGHTNESS > $ROOT_BRIGHTNESS/brightness

